name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  oxlint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@0.10.3 --deny-warnings # change to the latest release